server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/emason-usuario
    username: root
    password: root
  security:
    user:
      name: yeison
      password: yeison

  jpa:
    hibernate:
      ddl-auto: update